# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6986747b13df1402f85f7f3a2598cf4e640b54e6c9afbd38012ce31e2339fec62993fa120d7aed9a5c3932d23add394f350304a07b97d17cd00496301a5b47ce
  provider: AWS
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: eu-central-1
  # host: http://localhost:3000


test:
  secret_key_base: 14258955ba7e9e89a60eafb362087476efe7c985d59a880fee826b6b4139784ac6d6abc0600d0b2b04a7c99e7aa292da55719eb84f70bd722e482216005a3926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  provider: <%= ENV["PROVIDER"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["REGION"] %>
 
